/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 系统健康检查
         * @description 健康检查。
         */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取当前配置
         * @description 获取当前配置。
         */
        get: operations["get_settings_api_settings_get"];
        /**
         * 更新阈值配置
         * @description 更新阈值配置。
         */
        put: operations["update_settings_api_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/csrf-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取CSRF令牌
         * @description 获取 CSRF token 并设置双提交 cookie。
         *
         *     双提交模式：cookie + X-CSRFToken 头比对。
         *     cookie 设为 HttpOnly + SameSite=Lax，JS 从响应体读取 token。
         */
        get: operations["get_csrf_token_api_csrf_token_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/traffic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取实时流量统计
         * @description 获取实时流量统计。
         */
        get: operations["get_traffic_api_traffic_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/traffic/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取流量历史数据
         * @description 获取流量历史数据。
         */
        get: operations["get_traffic_history_api_traffic_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询告警列表（支持分页和级别筛选）
         * @description 获取告警列表。
         */
        get: operations["get_alerts_api_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取告警统计
         * @description 获取告警统计。
         */
        get: operations["get_alert_stats_api_alerts_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取所有任务状态
         * @description 获取所有任务状态。
         */
        get: operations["list_tasks_api_tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{name}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 启动指定任务
         * @description 启动指定任务。
         */
        post: operations["start_task_api_tasks__name__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{name}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 停止指定任务
         * @description 停止指定任务。
         */
        post: operations["stop_task_api_tasks__name__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取可用模型列表
         * @description 获取可用模型列表。
         */
        get: operations["list_models_api_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/train": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 启动模型训练
         * @description 启动模型训练。
         */
        post: operations["start_training_api_models_train_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/train/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取训练状态
         * @description 获取训练状态。
         */
        get: operations["get_train_status_api_models_train_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 删除指定模型
         * @description 删除指定模型。
         */
        delete: operations["delete_model_api_models__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取可用剧本列表
         * @description 获取可用剧本列表。
         */
        get: operations["list_scenarios_api_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 启动指定剧本
         * @description 启动指定剧本。
         */
        post: operations["start_scenario_api_scenarios_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 停止当前剧本
         * @description 停止当前剧本。
         */
        post: operations["stop_scenario_api_scenarios_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tls/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * TLS异常分析
         * @description TLS 异常分析。
         */
        get: operations["analyze_tls_api_tls_analyze_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payload/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 载荷分析
         * @description 载荷分析。
         */
        post: operations["analyze_payload_api_payload_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AlertListResponse
         * @description 告警列表响应。
         * @example {
         *       "alerts": [],
         *       "total": 0
         *     }
         */
        AlertListResponse: {
            /** Alerts */
            alerts: components["schemas"]["AlertResponse"][];
            /** Total */
            total: number;
        };
        /**
         * AlertResponse
         * @description 单条告警响应。
         * @example {
         *       "attack_type": "ddos",
         *       "confidence": 0.95,
         *       "detail": {},
         *       "dst_ip": "10.0.0.1",
         *       "id": "1",
         *       "severity": "high",
         *       "src_ip": "192.168.1.100",
         *       "timestamp": "2026-01-01T00:00:00"
         *     }
         */
        AlertResponse: {
            /** Id */
            id: string;
            /** Timestamp */
            timestamp: string;
            /** Src Ip */
            src_ip: string;
            /** Dst Ip */
            dst_ip: string;
            /** Attack Type */
            attack_type: string;
            /** Confidence */
            confidence: number;
            /**
             * Severity
             * @default medium
             */
            severity: string;
            /** Detail */
            detail?: {
                [key: string]: unknown;
            };
        };
        /**
         * AlertStatsResponse
         * @description 告警统计响应。
         */
        AlertStatsResponse: {
            /**
             * Total Alerts
             * @default 0
             */
            total_alerts: number;
            /** Alerts By Type */
            alerts_by_type?: {
                [key: string]: number;
            };
            /** Alerts By Severity */
            alerts_by_severity?: {
                [key: string]: number;
            };
            /** Recent Alerts */
            recent_alerts?: components["schemas"]["AlertResponse"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description 健康检查响应。
         * @example {
         *       "status": "ok",
         *       "uptime_seconds": 3600,
         *       "version": "0.2.0"
         *     }
         */
        HealthResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
            /**
             * Version
             * @default 0.2.0
             */
            version: string;
            /**
             * Uptime Seconds
             * @default 0
             */
            uptime_seconds: number;
        };
        /**
         * MessageResponse
         * @description 通用消息响应。
         * @example {
         *       "message": "操作成功",
         *       "status": "ok"
         *     }
         */
        MessageResponse: {
            /** Message */
            message: string;
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /**
         * ModelInfoResponse
         * @description 模型信息响应。
         */
        ModelInfoResponse: {
            /** Name */
            name: string;
            /** Version */
            version: string;
            /** Created At */
            created_at: string;
            /** Metrics */
            metrics?: {
                [key: string]: unknown;
            };
        };
        /**
         * ModelListResponse
         * @description 模型列表响应。
         */
        ModelListResponse: {
            /** Models */
            models: components["schemas"]["ModelInfoResponse"][];
        };
        /**
         * PayloadAnalysisRequest
         * @description 载荷分析请求。
         */
        PayloadAnalysisRequest: {
            /**
             * Data
             * @description 待分析载荷数据（base64 或 hex）
             */
            data: string;
            /**
             * Format
             * @description 数据格式: base64 | hex
             * @default hex
             */
            format: string;
        };
        /**
         * PayloadAnalysisResponse
         * @description 载荷分析响应。
         */
        PayloadAnalysisResponse: {
            /** Findings */
            findings?: {
                [key: string]: unknown;
            }[];
            /**
             * Risk Score
             * @default 0
             */
            risk_score: number;
            /**
             * Summary
             * @default
             */
            summary: string;
        };
        /**
         * ScenarioInfoResponse
         * @description 剧本信息响应。
         */
        ScenarioInfoResponse: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Tasks */
            tasks: string[];
        };
        /**
         * ScenarioListResponse
         * @description 剧本列表响应。
         */
        ScenarioListResponse: {
            /** Scenarios */
            scenarios: components["schemas"]["ScenarioInfoResponse"][];
        };
        /**
         * ScenarioStartRequest
         * @description 剧本启动请求。
         */
        ScenarioStartRequest: {
            /**
             * Scenario
             * @description 剧本名称: demo | full | attack
             */
            scenario: string;
        };
        /**
         * SettingsResponse
         * @description 配置响应。
         * @example {
         *       "auth_enabled": false,
         *       "ml_config": {
         *         "model_type": "xgboost"
         *       },
         *       "thresholds": {
         *         "ddos_threshold": 500,
         *         "port_scan_threshold": 100
         *       }
         *     }
         */
        SettingsResponse: {
            /** Thresholds */
            thresholds?: {
                [key: string]: number;
            };
            /** Ml Config */
            ml_config?: {
                [key: string]: unknown;
            };
            /**
             * Auth Enabled
             * @default false
             */
            auth_enabled: boolean;
        };
        /**
         * TaskActionRequest
         * @description 任务启动/停止请求。
         */
        TaskActionRequest: {
            /**
             * Duration
             * @description 限时任务运行秒数（仅 TIMED 类型）
             */
            duration?: number | null;
        };
        /**
         * TaskListResponse
         * @description 任务列表响应。
         */
        TaskListResponse: {
            /** Tasks */
            tasks: components["schemas"]["TaskStatusResponse"][];
        };
        /**
         * TaskStatusResponse
         * @description 单个任务状态响应。
         */
        TaskStatusResponse: {
            /** Name */
            name: string;
            /**
             * Kind
             * @description continuous | timed
             */
            kind: string;
            /**
             * Status
             * @description idle | running | stopping | finished | failed
             */
            status: string;
            /**
             * Elapsed
             * @default 0
             */
            elapsed: number;
            /** Error */
            error?: string | null;
        };
        /**
         * ThresholdUpdateRequest
         * @description 阈值更新请求。
         */
        ThresholdUpdateRequest: {
            /**
             * Key
             * @description 阈值键名
             */
            key: string;
            /**
             * Value
             * @description 阈值新值
             */
            value: number;
        };
        /**
         * TlsAnalysisResponse
         * @description TLS 分析响应。
         */
        TlsAnalysisResponse: {
            /** Anomalies */
            anomalies?: {
                [key: string]: unknown;
            }[];
            /** Summary */
            summary?: {
                [key: string]: unknown;
            };
        };
        /**
         * TrafficHistoryResponse
         * @description 流量历史响应。
         */
        TrafficHistoryResponse: {
            /** Timestamps */
            timestamps?: string[];
            /** Packets Per Second */
            packets_per_second?: number[];
        };
        /**
         * TrafficStatsResponse
         * @description 流量统计响应。
         * @example {
         *       "avg_packet_size": 512,
         *       "packets_per_second": 150.5,
         *       "protocol_distribution": {
         *         "ICMP": 500,
         *         "TCP": 8000,
         *         "UDP": 1500
         *       },
         *       "top_destinations": [],
         *       "top_sources": [],
         *       "total_packets": 10000
         *     }
         */
        TrafficStatsResponse: {
            /**
             * Total Packets
             * @default 0
             */
            total_packets: number;
            /**
             * Packets Per Second
             * @default 0
             */
            packets_per_second: number;
            /**
             * Avg Packet Size
             * @default 0
             */
            avg_packet_size: number;
            /** Protocol Distribution */
            protocol_distribution?: {
                [key: string]: number;
            };
            /** Top Sources */
            top_sources?: {
                [key: string]: unknown;
            }[];
            /** Top Destinations */
            top_destinations?: {
                [key: string]: unknown;
            }[];
        };
        /**
         * TrainRequest
         * @description 训练请求。
         */
        TrainRequest: {
            /**
             * Dataset
             * @description 训练数据集路径
             */
            dataset: string;
            /**
             * Epochs
             * @description 训练轮数
             * @default 10
             */
            epochs: number;
        };
        /**
         * TrainStatusResponse
         * @description 训练状态响应。
         * @example {
         *       "epoch": 5,
         *       "progress": 0.5,
         *       "status": "training",
         *       "total_epochs": 10
         *     }
         */
        TrainStatusResponse: {
            /**
             * Status
             * @description idle | training | completed | failed
             */
            status: string;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /**
             * Epoch
             * @default 0
             */
            epoch: number;
            /**
             * Total Epochs
             * @default 0
             */
            total_epochs: number;
            /** Error */
            error?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    update_settings_api_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThresholdUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_csrf_token_api_csrf_token_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_traffic_api_traffic_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrafficStatsResponse"];
                };
            };
        };
    };
    get_traffic_history_api_traffic_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrafficHistoryResponse"];
                };
            };
        };
    };
    get_alerts_api_alerts_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_alert_stats_api_alerts_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertStatsResponse"];
                };
            };
        };
    };
    list_tasks_api_tasks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskListResponse"];
                };
            };
        };
    };
    start_task_api_tasks__name__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_task_api_tasks__name__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_api_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelListResponse"];
                };
            };
        };
    };
    start_training_api_models_train_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrainRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_train_status_api_models_train_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainStatusResponse"];
                };
            };
        };
    };
    delete_model_api_models__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scenarios_api_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioListResponse"];
                };
            };
        };
    };
    start_scenario_api_scenarios_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_scenario_api_scenarios_stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    analyze_tls_api_tls_analyze_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TlsAnalysisResponse"];
                };
            };
        };
    };
    analyze_payload_api_payload_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PayloadAnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PayloadAnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
