/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 系统健康检查
         * @description 系统健康检查 — 对齐旧 Flask /api/health 返回格式。
         *
         *     组件：database / capture / ml_model / memory / sse / threads
         */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 环境自检
         * @description 环境自检：Python 版本、依赖包、Npcap、模型文件、数据文件。
         *
         *     数据目录取自 `Settings.data_dir`（而非硬算项目根），这样
         *     `CAMPUS_IDS_DATA_DIR` 指向别处时自检结果与实际运行目录一致。
         */
        get: operations["environment_check_api_check_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取当前配置
         * @description 获取当前配置 — 从 Settings 单例读取。
         */
        get: operations["get_settings_endpoint_api_settings_get"];
        /**
         * 更新阈值配置
         * @description 更新阈值配置 — 运行期覆盖 + DB 持久化 + 检测器热重建。
         */
        put: operations["update_settings_api_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/csrf-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取CSRF令牌
         * @description 获取 CSRF token 并设置双提交 cookie。
         *
         *     双提交模式：cookie + X-CSRFToken 头比对。
         *     cookie 设为 HttpOnly + SameSite=Lax，JS 从响应体读取 token。
         */
        get: operations["get_csrf_token_api_csrf_token_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/traffic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取实时流量统计
         * @description 获取实时流量统计数据（从 RuntimeState 读取内存中的当前值）。
         */
        get: operations["get_traffic_api_traffic_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/traffic/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取流量历史数据
         * @description 获取流量历史数据（从 SQLite traffic_history 表查询）。
         */
        get: operations["get_traffic_history_api_traffic_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询告警列表（支持分页和级别筛选）
         * @description 获取告警列表（从 SQLite alerts 表查询）。
         */
        get: operations["get_alerts_api_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取告警统计
         * @description 获取告警统计（总数、类型分布、级别分布）。
         */
        get: operations["get_alert_stats_api_alerts_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取所有任务状态
         * @description 获取所有任务状态。
         *
         *     取代旧端点：
         *     - GET /api/capture/status
         *     - GET /api/capture/enhanced-status
         *     - GET /api/detector/status
         *     - GET /api/attack/status
         *     - GET /api/auto/status
         *     - GET /api/dual/stats
         *     - GET /api/model/train-status
         */
        get: operations["list_tasks_api_tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{name}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 启动指定任务
         * @description 启动指定任务。
         *
         *     限时任务可指定 duration（秒），未指定则使用任务默认时长。
         *     连续任务忽略 duration 参数。
         *
         *     取代旧端点：
         *     - POST /api/capture/start
         *     - POST /api/capture/start-enhanced
         *     - POST /api/detector/start
         *     - POST /api/attack/start
         *     - POST /api/auto/start
         *     - POST /api/demo/start
         *     - POST /api/dual/load
         *     - POST /api/model/train
         */
        post: operations["start_task_api_tasks__name__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{name}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 停止指定任务
         * @description 停止指定任务（幂等）。
         *
         *     即使任务未在运行也返回成功，与旧端点行为一致。
         *
         *     取代旧端点：
         *     - POST /api/capture/stop
         *     - POST /api/capture/stop-enhanced
         *     - POST /api/detector/stop
         *     - POST /api/attack/stop
         *     - POST /api/dual/stop
         */
        post: operations["stop_task_api_tasks__name__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取可用模型列表
         * @description 获取可用模型列表 — 从 registry.json 读取。
         */
        get: operations["list_models_api_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/train": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 启动模型训练
         * @description 启动模型训练 —— 委托 `TaskRegistry` 的 `train` 任务（T2.13）。
         *
         *     三步保护：
         *     1. `confirm=true` 必填，否则 400 且不启动；
         *     2. 已在运行时返回 409（判据来自 TaskRegistry，不是本地状态机）；
         *     3. 启动前备份三个产物到 `<data_dir>/training_backup/<时间戳>/`。
         *
         *     `epochs` 仅用于判定 quick 模式（≤3），不直接等于训练轮数 ——
         *     训练链路的轮数由数据集配置决定（D4：不重构训练链路内部）。
         */
        post: operations["start_training_api_models_train_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/train/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取训练状态
         * @description 获取训练状态 —— 真相源是 `TaskRegistry`（T2.13）。
         *
         *     状态映射（TaskRegistry → 本响应）：
         *     `idle`→`idle`、`running`→`training`、`finished`→`completed`、`failed`→`failed`。
         *
         *     `progress` 由任务窗口 elapsed/duration 算出而非硬编码：
         *     训练任务在本架构里是 TIMED 任务（窗口时长 = `default_duration`，默认 120s），
         *     所以它是"任务窗口进度"而不是"训练收敛进度" —— 训练链路内部进度需要
         *     改 `model/train.py` 才能拿到，属 D4 范围外。
         */
        get: operations["get_train_status_api_models_train_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 删除指定模型
         * @description 删除指定模型 — 从 registry.json 移除并删除 run 目录。
         */
        delete: operations["delete_model_api_models__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取可用剧本列表
         * @description 获取可用剧本列表（供前端抽屉渲染，替代硬编码按钮）。
         */
        get: operations["list_scenarios_api_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 启动指定剧本
         * @description 启动指定剧本（按序执行子任务，任一失败则整体失败并回滚）。
         */
        post: operations["start_scenario_api_scenarios_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 停止指定剧本
         * @description 停止指定剧本（停止所有子任务，幂等）。
         */
        post: operations["stop_scenario_api_scenarios_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tls/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * TLS异常分析
         * @description TLS 异常分析（聚合统计 + 可疑记录摘要）。
         */
        get: operations["analyze_tls_api_tls_analyze_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tls/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * TLS加密流量统计
         * @description 获取 TLS 加密流量统计。
         */
        get: operations["get_tls_stats_api_tls_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tls/suspicious": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取可疑TLS记录
         * @description 获取可疑 TLS 记录列表。
         */
        get: operations["get_tls_suspicious_api_tls_suspicious_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payload/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 载荷送检（旧路径）
         * @description 对 HTTP 载荷执行应用层检测（SQL 注入 + XSS）。
         *
         *     保留旧路径 /api/payload/check 以兼容现有客户端。
         */
        post: operations["check_payload_api_payload_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payload/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 载荷分析
         * @description 对 HTTP 载荷执行应用层检测（SQL 注入 + XSS）。
         */
        post: operations["analyze_payload_api_payload_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * SSE 实时事件流
         * @description 单条 SSE 事件流。
         *
         *     通过 ?topics= 参数选择订阅主题。**帧的 `event:` 名与 topic 名相同。**
         */
        get: operations["event_stream_api_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/cleanup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 清理过期历史数据
         * @description 清理过期历史数据 — 删除超过指定天数的告警和流量记录。
         *
         *     对齐旧 /api/cleanup 端点行为。
         */
        post: operations["cleanup_data_api_admin_cleanup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 导出流量数据到CSV
         * @description 导出流量数据到 CSV — 从 SQLite 查询写入 traffic_stats.csv。
         *
         *     对齐旧 /api/save 端点行为。
         */
        post: operations["export_data_api_admin_export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 会话登录
         * @description 用户名+密码登录，成功后写入会话。
         */
        post: operations["login_api_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 会话登出
         * @description 清除会话认证信息。
         */
        post: operations["logout_api_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 修改密码
         * @description 修改当前用户密码。需提供旧密码验证。
         */
        post: operations["change_password_api_change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AlertListResponse
         * @description 告警列表响应。
         * @example {
         *       "alerts": [],
         *       "limit": 50,
         *       "offset": 0,
         *       "total": 0
         *     }
         */
        AlertListResponse: {
            /** Alerts */
            alerts: components["schemas"]["AlertResponse"][];
            /** Total */
            total: number;
            /**
             * Limit
             * @default 50
             */
            limit: number;
            /**
             * Offset
             * @default 0
             */
            offset: number;
        };
        /**
         * AlertResponse
         * @description 单条告警响应。
         * @example {
         *       "attack_type": "ddos",
         *       "id": 1,
         *       "level": "high",
         *       "message": "DDoS attack detected",
         *       "ml_confidence": 0.95,
         *       "time": "2026-01-01 00:00:00"
         *     }
         */
        AlertResponse: {
            /** Id */
            id: number;
            /** Time */
            time: string;
            /** Level */
            level: string;
            /** Attack Type */
            attack_type: string;
            /** Message */
            message: string;
            /**
             * Ml Confidence
             * @default 0
             */
            ml_confidence: number;
        };
        /**
         * AlertStatsResponse
         * @description 告警统计响应。
         */
        AlertStatsResponse: {
            /**
             * Total Alerts
             * @default 0
             */
            total_alerts: number;
            /** Alerts By Type */
            alerts_by_type?: {
                [key: string]: number;
            };
            /** Alerts By Severity */
            alerts_by_severity?: {
                [key: string]: number;
            };
        };
        /**
         * ChangePasswordRequest
         * @description 修改密码请求。
         */
        ChangePasswordRequest: {
            /** Old Password */
            old_password: string;
            /** New Password */
            new_password: string;
        };
        /**
         * ChangePasswordResponse
         * @description 修改密码响应。
         */
        ChangePasswordResponse: {
            /**
             * Status
             * @default success
             */
            status: string;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /**
         * CheckResponse
         * @description 环境自检响应 — 对齐旧 Flask /api/check 返回格式。
         */
        CheckResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Python */
            python?: {
                [key: string]: unknown;
            };
            /** Dependencies */
            dependencies?: {
                [key: string]: unknown;
            };
            /** Capture */
            capture?: {
                [key: string]: unknown;
            };
            /** Model Files */
            model_files?: {
                [key: string]: unknown;
            }[];
            /** Data Files */
            data_files?: {
                [key: string]: unknown;
            }[];
        };
        /**
         * CleanupRequest
         * @description 清理请求。
         */
        CleanupRequest: {
            /**
             * Days
             * @description 保留最近N天的数据
             * @default 7
             */
            days: number;
        };
        /**
         * CleanupResponse
         * @description 清理响应。
         */
        CleanupResponse: {
            /**
             * Status
             * @default success
             */
            status: string;
            /**
             * Alerts Deleted
             * @default 0
             */
            alerts_deleted: number;
            /**
             * Traffic Deleted
             * @default 0
             */
            traffic_deleted: number;
        };
        /**
         * ExportResponse
         * @description 导出响应。
         */
        ExportResponse: {
            /**
             * Status
             * @default success
             */
            status: string;
            /**
             * Message
             * @default
             */
            message: string;
            /**
             * Rows
             * @default 0
             */
            rows: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description 健康检查响应 — 对齐旧 Flask /api/health 返回格式。
         * @example {
         *       "components": {
         *         "capture": {
         *           "status": "stopped"
         *         },
         *         "database": {
         *           "status": "ok"
         *         },
         *         "ml_model": {
         *           "model_loaded": false
         *         }
         *       },
         *       "status": "healthy",
         *       "timestamp": "2026-01-01 12:00:00",
         *       "uptime_seconds": 3600
         *     }
         */
        HealthResponse: {
            /**
             * Status
             * @default healthy
             */
            status: string;
            /**
             * Timestamp
             * @default
             */
            timestamp: string;
            /**
             * Uptime Seconds
             * @default 0
             */
            uptime_seconds: number;
            /** Components */
            components?: {
                [key: string]: unknown;
            };
        };
        /**
         * LoginRequest
         * @description 登录请求。
         */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /**
         * LoginResponse
         * @description 登录响应。
         */
        LoginResponse: {
            /**
             * Status
             * @default success
             */
            status: string;
            /**
             * Message
             * @default
             */
            message: string;
            /**
             * Username
             * @default
             */
            username: string;
        };
        /**
         * LogoutResponse
         * @description 登出响应。
         */
        LogoutResponse: {
            /**
             * Status
             * @default success
             */
            status: string;
            /**
             * Message
             * @default 已登出
             */
            message: string;
        };
        /**
         * MessageResponse
         * @description 通用消息响应。
         * @example {
         *       "message": "操作成功",
         *       "status": "ok"
         *     }
         */
        MessageResponse: {
            /** Message */
            message: string;
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /**
         * ModelInfoResponse
         * @description 模型信息响应。
         */
        ModelInfoResponse: {
            /** Name */
            name: string;
            /** Version */
            version: string;
            /** Created At */
            created_at: string;
            /** Metrics */
            metrics?: {
                [key: string]: unknown;
            };
        };
        /**
         * ModelListResponse
         * @description 模型列表响应。
         */
        ModelListResponse: {
            /** Models */
            models: components["schemas"]["ModelInfoResponse"][];
        };
        /**
         * PayloadAnalysisRequest
         * @description 载荷分析请求。
         */
        PayloadAnalysisRequest: {
            /**
             * Payload
             * @description 待分析的 HTTP 载荷字符串
             */
            payload: string;
        };
        /**
         * PayloadAnalysisResponse
         * @description 载荷分析响应。
         *
         *     ⚠️ 字段名必须与**旧实现**一致：`web/bp_capture.py:368-373` 返回
         *     `{'alerts': [...], 'is_anomaly': bool, 'payload_length': len(payload)}`。
         *
         *     2026-09-17 参数级契约门禁（`tests/contract/specdiff.py`）抓到本类此前用了
         *     `threats` / `is_malicious` 两个**新名字**，并把 `payload_length` 整个丢掉 ——
         *     旧客户端的 `addEventListener` 式取值会全部拿到 `undefined`。这正是
         *     "路径保住了、响应契约没保住"的典型：路径级门禁完全看不见。
         */
        PayloadAnalysisResponse: {
            /**
             * Alerts
             * @description 告警列表
             */
            alerts?: string[];
            /**
             * Is Anomaly
             * @description 是否异常
             * @default false
             */
            is_anomaly: boolean;
            /**
             * Payload Length
             * @description 载荷长度
             * @default 0
             */
            payload_length: number;
        };
        /**
         * ScenarioInfoResponse
         * @description 剧本信息响应。
         */
        ScenarioInfoResponse: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /**
             * Steps
             * @description 剧本子任务序列
             */
            steps: string[];
        };
        /**
         * ScenarioListResponse
         * @description 剧本列表响应。
         */
        ScenarioListResponse: {
            /** Scenarios */
            scenarios: components["schemas"]["ScenarioInfoResponse"][];
        };
        /**
         * ScenarioStartRequest
         * @description 剧本启动请求。
         */
        ScenarioStartRequest: {
            /**
             * Scenario
             * @description 剧本名称: demo | full | attack
             */
            scenario: string;
            /**
             * Duration
             * @description 限时子任务运行秒数（仅影响 TIMED 类型子任务）
             */
            duration?: number | null;
        };
        /**
         * ScenarioStopRequest
         * @description 剧本停止请求。
         */
        ScenarioStopRequest: {
            /**
             * Scenario
             * @description 剧本名称: demo | full | attack
             */
            scenario: string;
        };
        /**
         * SettingsResponse
         * @description 配置响应 — 对齐 Settings 类字段。
         * @example {
         *       "alert_config": {
         *         "max_alert_api_return": 20
         *       },
         *       "auth_enabled": false,
         *       "ml_config": {
         *         "ml_conf_high": 0.7,
         *         "ml_interval_sec": 5
         *       },
         *       "thresholds": {
         *         "ddos_threshold": 500,
         *         "port_scan_threshold": 50
         *       },
         *       "web_config": {
         *         "web_port": 5000
         *       }
         *     }
         */
        SettingsResponse: {
            /**
             * Thresholds
             * @description 规则检测阈值
             */
            thresholds?: {
                [key: string]: unknown;
            };
            /**
             * Ml Config
             * @description ML 检测配置
             */
            ml_config?: {
                [key: string]: unknown;
            };
            /**
             * Web Config
             * @description Web 面板配置
             */
            web_config?: {
                [key: string]: unknown;
            };
            /**
             * Auth Enabled
             * @default false
             */
            auth_enabled: boolean;
            /**
             * Alert Config
             * @description 告警配置
             */
            alert_config?: {
                [key: string]: unknown;
            };
        };
        /**
         * TaskActionRequest
         * @description 任务启动/停止请求。
         */
        TaskActionRequest: {
            /**
             * Duration
             * @description 限时任务运行秒数（仅 TIMED 类型）
             */
            duration?: number | null;
        };
        /**
         * TaskListResponse
         * @description 任务列表响应。
         */
        TaskListResponse: {
            /** Tasks */
            tasks: components["schemas"]["TaskStatusResponse"][];
        };
        /**
         * TaskStatusResponse
         * @description 单个任务状态响应。
         */
        TaskStatusResponse: {
            /** Name */
            name: string;
            /**
             * Kind
             * @description continuous | timed
             */
            kind: string;
            /**
             * Status
             * @description idle | running | stopping | finished | failed
             */
            status: string;
            /**
             * Elapsed
             * @default 0
             */
            elapsed: number;
            /** Error */
            error?: string | null;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Default Duration
             * @description 限时任务默认时长(秒)
             */
            default_duration?: number | null;
        };
        /**
         * ThresholdUpdateRequest
         * @description 阈值更新请求。
         */
        ThresholdUpdateRequest: {
            /**
             * Key
             * @description 阈值键名
             */
            key: string;
            /**
             * Value
             * @description 阈值新值
             */
            value: number;
        };
        /**
         * TlsAnalysisResponse
         * @description TLS 分析响应。
         */
        TlsAnalysisResponse: {
            /** Anomalies */
            anomalies?: {
                [key: string]: unknown;
            }[];
            /** Summary */
            summary?: {
                [key: string]: unknown;
            };
        };
        /**
         * TrafficHistoryRecord
         * @description 单条流量历史记录。
         */
        TrafficHistoryRecord: {
            /** Id */
            id: number;
            /** Time */
            time: string;
            /** Qps */
            qps?: number | null;
            /** Connections */
            connections?: number | null;
            /** Packet Count */
            packet_count?: number | null;
            /** Port Count */
            port_count?: number | null;
            /** Src Ip Count */
            src_ip_count?: number | null;
            /** Alert */
            alert?: string | null;
        };
        /**
         * TrafficHistoryResponse
         * @description 流量历史响应。
         */
        TrafficHistoryResponse: {
            /** History */
            history?: components["schemas"]["TrafficHistoryRecord"][];
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Limit
             * @default 60
             */
            limit: number;
            /**
             * Offset
             * @default 0
             */
            offset: number;
        };
        /**
         * TrafficStatsResponse
         * @description 流量统计响应。
         * @example {
         *       "alert": "",
         *       "connections": 42,
         *       "dns_packets": 50,
         *       "packet_count": 10000,
         *       "port_count": 15,
         *       "qps": 150.5,
         *       "src_ip_count": 8,
         *       "syn_packets": 500,
         *       "timestamp": "2026-01-01T00:00:00",
         *       "udp_packets": 200
         *     }
         */
        TrafficStatsResponse: {
            /**
             * Qps
             * @default 0
             */
            qps: number;
            /**
             * Connections
             * @default 0
             */
            connections: number;
            /**
             * Alert
             * @default
             */
            alert: string;
            /**
             * Timestamp
             * @default
             */
            timestamp: string;
            /**
             * Packet Count
             * @default 0
             */
            packet_count: number;
            /**
             * Port Count
             * @default 0
             */
            port_count: number;
            /**
             * Src Ip Count
             * @default 0
             */
            src_ip_count: number;
            /**
             * Syn Packets
             * @default 0
             */
            syn_packets: number;
            /**
             * Udp Packets
             * @default 0
             */
            udp_packets: number;
            /**
             * Dns Packets
             * @default 0
             */
            dns_packets: number;
        };
        /**
         * TrainRequest
         * @description 训练请求（T2.13 起带破坏性操作保护）。
         */
        TrainRequest: {
            /**
             * Dataset
             * @description 训练数据集标识（透传给训练链路 dataset_type）
             * @default auto
             */
            dataset: string;
            /**
             * Epochs
             * @description 训练轮数；≤3 视为 quick 模式
             * @default 10
             */
            epochs: number;
            /**
             * Confirm
             * @description **必填确认位**。训练会覆盖 model.pkl / evaluation_report.txt / confusion_matrix.png，未传 `confirm=true` 时请求被拒绝（400），不会启动训练。启动前会自动备份这三个产物到 `<data_dir>/training_backup/<时间戳>/`。
             * @default false
             */
            confirm: boolean;
        };
        /**
         * TrainStatusResponse
         * @description 训练状态响应。
         *
         *     `status` 的真相源是 `TaskRegistry` 里 `train` 任务的状态
         *     （T2.13 收敛；此前是 `api/models.py` 的模块级状态机，与任务编排互不感知）。
         * @example {
         *       "epoch": 5,
         *       "progress": 0.5,
         *       "status": "training",
         *       "total_epochs": 10
         *     }
         */
        TrainStatusResponse: {
            /**
             * Status
             * @description idle | training | completed | failed
             */
            status: string;
            /**
             * Progress
             * @description 进度 0.0–1.0，由任务窗口已耗时/总时长算出（非硬编码）
             * @default 0
             */
            progress: number;
            /**
             * Epoch
             * @default 0
             */
            epoch: number;
            /**
             * Total Epochs
             * @default 0
             */
            total_epochs: number;
            /** Error */
            error?: string | null;
            /**
             * Elapsed Seconds
             * @description 任务已运行秒数（来自 TaskRegistry）
             */
            elapsed_seconds?: number | null;
            /**
             * Duration Seconds
             * @description 任务窗口时长（来自 TaskRegistry）
             */
            duration_seconds?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    environment_check_api_check_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckResponse"];
                };
            };
        };
    };
    get_settings_endpoint_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    update_settings_api_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThresholdUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_csrf_token_api_csrf_token_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_traffic_api_traffic_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrafficStatsResponse"];
                };
            };
        };
    };
    get_traffic_history_api_traffic_history_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrafficHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_alerts_api_alerts_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description 级别筛选: high/medium/low/all */
                level?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_alert_stats_api_alerts_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertStatsResponse"];
                };
            };
        };
    };
    list_tasks_api_tasks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskListResponse"];
                };
            };
        };
    };
    start_task_api_tasks__name__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_task_api_tasks__name__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_api_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelListResponse"];
                };
            };
        };
    };
    start_training_api_models_train_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrainRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_train_status_api_models_train_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainStatusResponse"];
                };
            };
        };
    };
    delete_model_api_models__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scenarios_api_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioListResponse"];
                };
            };
        };
    };
    start_scenario_api_scenarios_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_scenario_api_scenarios_stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioStopRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_tls_api_tls_analyze_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TlsAnalysisResponse"];
                };
            };
        };
    };
    get_tls_stats_api_tls_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_tls_suspicious_api_tls_suspicious_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_payload_api_payload_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PayloadAnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PayloadAnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_payload_api_payload_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PayloadAnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PayloadAnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    event_stream_api_stream_get: {
        parameters: {
            query?: {
                /** @description 订阅主题（逗号分隔） */
                topics?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cleanup_data_api_admin_cleanup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CleanupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CleanupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_data_api_admin_export_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportResponse"];
                };
            };
        };
    };
    login_api_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
        };
    };
    change_password_api_change_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangePasswordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
